import barba from '@barba/core'
import { gsap } from 'gsap/dist/gsap.js'
import { ScrollToPlugin } from 'gsap/dist/ScrollToPlugin.js'
import { ScrollTrigger } from 'gsap/dist/ScrollTrigger.js'
import { Curtains, Plane } from 'curtainsjs'
import Rellax from 'rellax'
import Plyr from 'plyr'
import main from '../css/main'